### ISSUE TITLE
It doesn't work，I don't know why

### ISSUE THREAD

**Issue by FengLuLuL** [pyushkevich/greedy#34]
Hello.

I met a problem. could you pls help me?

My system is ubuntu20.4 on the virtual machine.
I've built with the command make -j 8, 
[  6%] Built target text_to_hex
[ 30%] Built target docs_to_hex
[ 36%] Built target test_accum
[ 63%] Built target greedyapi
[ 86%] Built target test_greedy
[ 86%] Built target greedy
[ 90%] Built target greedy_template_average
[100%] Built target multi_chunk_greedy
but nothing happened after running the command
greedy -d 3 -a \
    -m NCC 2x2x2 \
    -i /home/fll/Desktop/greedy/czzDTI.nii.gz /home/fll/Desktop/greedy/czzT1.nii.gz \
    -o /home/fll/Desktop/greedy/affine.mat \
    -ia-image-centers -n 100x50x10

When I use the command
> greedy -d 3 -a \
    -m NCC 2x2x2 \
    -i /home/fll/Desktop/greedy/czzDTI.nii.gz /home/fll/Desktop/greedy/czzT1.nii.gz \
    -o /home/fll/Desktop/greedy/affine.mat \
    -ia-image-centers -n 100x50x10
, the system says it can't be found.

**Comment by jilei-hao** [comment]
Is the path to greedy executable in your PATH environment variable? If not, you can make a link to the executable you just built in /usr/bin or /usr/local/bin.

Or just try using the path to your greedy executable. "/your/greedy/build/directory/greedy -d 3 ... "

**Comment by FengLuLuL** [comment]
Thank you for your reply.
I don't know if I did it right，I use the command
ln -s /home/fll/Desktop/greedy/build/greedy  /usr/bin
and I use the command，
ln -s /home/fll/Desktop/greedy/build/greedy  /usr/local/bin
it said the documents already existed.
After using these commands, I still can't use greedy.
I found that  /build/greedy and /usr/local/bin/greedy are 0 bytes, is that correct?

**Comment by jilei-hao** [comment]
Does anything happen if you execute `/home/fll/Desktop/greedy/build/greedy` ?

**Comment by FengLuLuL** [comment]
Thank you for your reply.
I have no way to run it.
It is a 0-byte plain text document.
This is the directory of my build folder：
CMakeCache.txt           GreedyVersion.cxx       stackg_usage_splat.h
CMakeFiles               install_manifest.txt    stackg_usage_voladd.h
cmake_install.cmake      ITKFactoryRegistration  stackg_usage_voliter.h
CPackConfig.cmake        libgreedyapi.a          stackg_usage_volmatch.h
CPackSourceConfig.cmake  Makefile                test_accum
CTestTestfile.cmake      multi_chunk_greedy      test_greedy
DartConfiguration.tcl    stackg_usage_init.h     Testing
greedy                   stackg_usage_main.h     text_to_hex
greedy_template_average  stackg_usage_recon.h

Was there something wrong with me installing greedy that caused this to happen?

**Comment by jilei-hao** [comment]
A lot of things can go wrong when building from source code. Can you try download this binary for Linux and see if it work for you? https://sourceforge.net/projects/greedy-reg/files/Nightly/greedy-nightly-Linux-gcc64.tar.gz/download

**Comment by jilei-hao** [comment]
After generating the warp image, you have to apply the warp to the moving image using the greedy reslicing command.

**Comment by FengLuLuL** [comment]
Thank you for your reply.
I've used the command
./greedy -d 3     
-rf /home/fll/Desktop/greedy/czzDTI.nii.gz     
-rm /home/fll/Desktop/greedy/czzT1.nii.gz /home/fll/Desktop/greedy/czzresliced.nii.gz     
-ri LABEL 0.2vox     
-r /home/fll/Desktop/greedy/warp.nii.gz /home/fll/Desktop/greedy/affine.mat

I don't have a segmented image.
The following prompt appears，
Executing with the default number of threads: 16

Is this already running out? But I don't think anything has changed in the image.

**Comment by jilei-hao** [comment]
The resliced image should be in `/home/fll/Desktop/greedy/czzresliced.nii.gz`
By saying you don't have a segmented image, do you mean this image: `/home/fll/Desktop/greedy/czzresliced.nii.gz` has never been created?

**Comment by FengLuLuL** [comment]
Thank you for your reply.
czzresliced.nii .gz exists.
I mean I don't have moving_seg.nii.gz，so I deleted the command
-rm moving_seg.nii.gz resliced_seg.nii.gz \

Is my command running failing because of this behavior?

**Comment by jilei-hao** [comment]
From your command:
`./greedy -d 3
-rf /home/fll/Desktop/greedy/czzDTI.nii.gz
-rm /home/fll/Desktop/greedy/czzT1.nii.gz /home/fll/Desktop/greedy/czzresliced.nii.gz
-ri LABEL 0.2vox
-r /home/fll/Desktop/greedy/warp.nii.gz /home/fll/Desktop/greedy/affine.mat`

What I understand is you want to relisce `czzT1.nii.gz` to the space of `czzDTI.nii.gz`, and store the resliced image to `czzresliced.nii.gz`. Is that correct?

If `Executing with the default number of threads: 16` was the only message printed out, without any error messages, then I think the execution was successful. When you mentioned "I don't think anything has changed in the image.", do you mean the resliced image has not been warped at all comparing to czzT1.nii.gz?

**Comment by FengLuLuL** [comment]
Thank you for your reply.
I want to apply the warp to the moving image，gets the image after registration.
I see the command given on the official website is
greedy -d 3 \
    -rf fixed.nii.gz \
    -rm moving.nii.gz resliced.nii.gz \
    -ri LABEL 0.2vox \
    -rm moving_seg.nii.gz resliced_seg.nii.gz \
    -r warp.nii.gz affine.mat  

but I didn't get the registered image.
Can you tell me what command I should use to get a registered image?

**Comment by jilei-hao** [comment]
The reslicing command is the correct command to use get a registered image.

The `-rm` parameter specify the input and output image. To use this command, put moving image as the input image, and put output image filename as the output image. After the execution, the registered image will be stored to the output image specific with the filename.

By saying you are not getting the registered image, do you mean the output image was not generated? Or has the output image not been warped at all?

**Comment by FengLuLuL** [comment]
Thank you for your reply.
I found the registered image and thank you very much.
However, the effect after registration is not very good. 
And I tried to use  -dof 7 but reported an error as follows, 
ABORTING PROGRAM DUE TO RUNTIME EXCEPTION -- DOF parameter only accepts 6 and 12 as values.
Is this because of the problem with the version?

**Comment by jilei-hao** [comment]
Can you pull the latest code and try again?
It was added 13 days ago in [27fe4275986d79caa93523c9e4039e4f97ffe5f5](https://github.com/pyushkevich/greedy/commit/27fe4275986d79caa93523c9e4039e4f97ffe5f5)

**Comment by FengLuLuL** [comment]
No more questions for now, thank you for your help.
