### ISSUE TITLE
What are the default parameters for registration in itk snap 3.6.0?

### ISSUE THREAD

**Issue by EgShes** [pyushkevich/greedy#36]
I did registration of 3d images in ITK-SNAP and it was great. Now I want to reproduce it using command line tool.

What parameters should I pass to get the same result?

I use the following settings:
- transformation model: rigid
- metric: mutual information
- multi-resolution schedule: coarsest level 16x, finest level 8x

![image](https://user-images.githubusercontent.com/42002290/195029139-96a8008d-7174-4acf-aed5-aa3d9172948e.png)

**Comment by EgShes** [comment]
ITK-SNAP version I use
![image](https://user-images.githubusercontent.com/42002290/195030815-3b0ccc71-1ab7-4058-bd55-822f7727c1ba.png)

**Comment by jilei-hao** [comment]
Hi, please see following:
transformation model: rigid `-dof 6`
metric: mutual information `-m NMI`
multi-resolution schedule: coarsest level 16x, finest level 8x `-n 100x100x0x0`
