### ISSUE TITLE
Can it work on Sinogram level for motion correction?

### ISSUE THREAD

**Issue by WenhongLan** [pyushkevich/greedy#39]
Hello all,

I tried to use greedy for image registration on sinogram level. my sinogram size is 520 x 50 x 11559 x 35 (int8). I configure the affine and deformable registration. I am following the quick start instruction of Greedy. and greedy can run for the lowest and intermediate resolution. But when working on full resolution, the greedy will be interrupted after finishing the intermediate resolution iterations (on Affine mode, no affine.mat output).

I am considering whether it is the hardware or the software restriction. May I ask does any hard restriction on the application level?

Additionally my hardware is Xeon Gold 6242R with 768 GB RAM.

Best regards
Wenhong Lan

**Comment by pyushkevich** [comment]
Hi, I've never tried it on anything that size. In principle you should have
enough memory. Have you tried subsampling the image along the large
direction, maybe to make it 510x50x1160x35 and then trying?

**Comment by WenhongLan** [comment]
Many thanks for you comments. I am testing with the down-sampling data, although we do not expect any down-sampling on the data.

Besides, we also test the dataset I mentioned with greedy in another workstation with 4TB RAM. And it still does not have outcome. But greedy works, at least from the log file. And I am considering whether the problems on the I/O function used by Greedy, such as the old version .mat format with the maximum size restriction.
