### ISSUE TITLE
Weird demofrmation following Quick Start guide

### ISSUE THREAD

**Issue by vzickus** [pyushkevich/greedy#7]
Following the quick start guide [here](https://sites.google.com/view/greedyreg/quick-start) and using -d 2 instead of -d 3, using the images provided in the _/matlab/diff_ directory, I get a weird deformation. Below shows (fixed, moving, warped) images from top to bottom. I also include the deformation field. Any ideas why this is the case?

![brain_fixed](https://user-images.githubusercontent.com/6878017/56653446-95b71d00-6685-11e9-9d65-fbe6520bb7d5.png)
![brain_moving](https://user-images.githubusercontent.com/6878017/56653451-96e84a00-6685-11e9-8fd2-70cb87771b2f.png)
![resliced](https://user-images.githubusercontent.com/6878017/56653457-98197700-6685-11e9-875c-61db4adac3cf.png)
[warp.nii.gz](https://github.com/pyushkevich/greedy/files/3111861/warp.nii.gz)

**Comment by pyushkevich** [comment]
Hello,

I cannot reproduce this error. Here are the commands I ran and reasonable-looking output that I get. Please check that you are using the current code.

`#!/bin/bash
greedy -d 2 -a -m NCC 2x2x2 -i brain_fixed.png brain_moving.png -o affine.mat -ia-image-centers -n 100x50x10`

`greedy -d 2 -m NCC 2x2 -i brain_fixed.png brain_moving.png -it affine.mat -o warp.nii.gz -n 100x50x10 -n 100x50x10`

`greedy -d 2 -rf brain_fixed.png -rm brain_moving.png reslice_brain_moving.png -r warp.nii.gz affine.mat`

![image](https://user-images.githubusercontent.com/1241691/56681013-665cdc00-6696-11e9-9e99-49ec9c248733.png)

Paul

**Comment by vzickus** [comment]
Ah, OK, I did not use "-n 100x50x10" twice like you show here. It works now.

Curiously, I tried reproducing the error with commands I used initially (just looking up the history in the terminal) and could not do it. Oh well!
